
-- =====================================================
-- STEP 1 — CREATE TABLES
-- =====================================================
 
CREATE TABLE OMNI_FLEX.DEPARTMENTS (
    DEPT_ID   VARCHAR2(10) PRIMARY KEY,
    DEPT_NAME VARCHAR2(50) NOT NULL,
    HOD_NAME  VARCHAR2(50) NOT NULL
);
 
CREATE TABLE OMNI_FLEX.SEMESTERS (
    SEMESTER_ID   VARCHAR2(10) PRIMARY KEY,
    SEMESTER_NAME VARCHAR2(20) NOT NULL,
    START_DATE    DATE,
    END_DATE      DATE,
    IS_CURRENT    NUMBER(1,0) DEFAULT 0
);
 
CREATE TABLE OMNI_FLEX.USERS (
    USER_ID          VARCHAR2(10) PRIMARY KEY,
    DEPT_ID          VARCHAR2(10),
    FIRST_NAME       VARCHAR2(20) NOT NULL,
    LAST_NAME        VARCHAR2(20) NOT NULL,
    EMAIL            VARCHAR2(50) NOT NULL,
    PASSWORD_HASH    VARCHAR2(100) NOT NULL,
    ROLE             VARCHAR2(10) NOT NULL,
    STATUS           VARCHAR2(10) DEFAULT 'Active',
    BATCH            NUMBER(4,0),
    DEGREE           VARCHAR2(20),
    DESIGNATION      VARCHAR2(30),
    OFFICE_ROOM      VARCHAR2(10),
    SPECIALIZATION   VARCHAR2(50),
    TA_PASSWORD_HASH VARCHAR2(100),
    GENDER           VARCHAR2(10),
    DOB              DATE,
    PHONE_NUMBER     VARCHAR2(15),
    ADDRESS          VARCHAR2(200),
    CITY             VARCHAR2(50),
    COUNTRY          VARCHAR2(50),
    CONSTRAINT CHK_USER_ROLE CHECK (ROLE IN ('Admin','Instructor','Student')),
    CONSTRAINT FK_USER_DEPT FOREIGN KEY (DEPT_ID) REFERENCES OMNI_FLEX.DEPARTMENTS(DEPT_ID)
);
 
CREATE TABLE OMNI_FLEX.COURSES (
    COURSE_ID   VARCHAR2(10) PRIMARY KEY,
    DEPT_ID     VARCHAR2(10),
    COURSE_NAME VARCHAR2(50) NOT NULL,
    CREDIT_HRS  NUMBER(1,0) NOT NULL,
    COURSE_TYPE VARCHAR2(10) NOT NULL,
    COURSE_CAT  VARCHAR2(15) NOT NULL,
    PRE_REQ_ID  VARCHAR2(10),
    IS_ACTIVE   NUMBER(1,0) DEFAULT 0,
    CONSTRAINT CHK_COURSE_TYPE CHECK (COURSE_TYPE IN ('Theory','Lab')),
    CONSTRAINT CHK_COURSE_CAT  CHECK (COURSE_CAT  IN ('Core','Elective')),
    CONSTRAINT FK_COURSE_DEPT  FOREIGN KEY (DEPT_ID)    REFERENCES OMNI_FLEX.DEPARTMENTS(DEPT_ID),
    CONSTRAINT FK_COURSE_PRE   FOREIGN KEY (PRE_REQ_ID) REFERENCES OMNI_FLEX.COURSES(COURSE_ID)
);
 
CREATE TABLE OMNI_FLEX.SECTIONS (
    SECTION_ID    VARCHAR2(10) PRIMARY KEY,
    SECTION_LABEL VARCHAR2(5),
    DEPARTMENT_ID VARCHAR2(10),
    DEGREE        VARCHAR2(10),
    BATCH         NUMBER(4,0),
    CR_ID         VARCHAR2(10),
    CONSTRAINT FK_SECTIONS_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES OMNI_FLEX.DEPARTMENTS(DEPT_ID),
    CONSTRAINT FK_SECTIONS_CR   FOREIGN KEY (CR_ID)         REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.SECTION_OFFERINGS (
    OFFERING_ID VARCHAR2(10) PRIMARY KEY,
    SECTION_ID  VARCHAR2(10) NOT NULL,
    COURSE_ID   VARCHAR2(10) NOT NULL,
    SEMESTER_ID VARCHAR2(10) NOT NULL,
    TEACHER_ID  VARCHAR2(10),
    SEATS       NUMBER,
    CONSTRAINT CHK_MAX_SEATS  CHECK (SEATS <= 50),
    CONSTRAINT UQ_OFFERING    UNIQUE (SECTION_ID, COURSE_ID, SEMESTER_ID),
    CONSTRAINT FK_SO_SECTION  FOREIGN KEY (SECTION_ID)  REFERENCES OMNI_FLEX.SECTIONS(SECTION_ID),
    CONSTRAINT FK_SO_COURSE   FOREIGN KEY (COURSE_ID)   REFERENCES OMNI_FLEX.COURSES(COURSE_ID),
    CONSTRAINT FK_SO_SEMESTER FOREIGN KEY (SEMESTER_ID) REFERENCES OMNI_FLEX.SEMESTERS(SEMESTER_ID),
    CONSTRAINT FK_SO_TEACHER  FOREIGN KEY (TEACHER_ID)  REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.SECTION_TAS (
    TA_ASSIGNMENT_ID VARCHAR2(10) PRIMARY KEY,
    SECTION_ID       VARCHAR2(10),
    TA_ID            VARCHAR2(10),
    COURSE_ID        VARCHAR2(10),
    SEMESTER_ID      VARCHAR2(10),
    ASSIGNED_BY      VARCHAR2(10),
    ASSIGNED_DATE    DATE DEFAULT SYSDATE,
    CONSTRAINT UQ_TA_ASSIGNMENT UNIQUE (SECTION_ID, TA_ID, COURSE_ID, SEMESTER_ID),
    CONSTRAINT FK_TA_SECTION  FOREIGN KEY (SECTION_ID)  REFERENCES OMNI_FLEX.SECTIONS(SECTION_ID),
    CONSTRAINT FK_TA_USER     FOREIGN KEY (TA_ID)       REFERENCES OMNI_FLEX.USERS(USER_ID),
    CONSTRAINT FK_TA_COURSE   FOREIGN KEY (COURSE_ID)   REFERENCES OMNI_FLEX.COURSES(COURSE_ID),
    CONSTRAINT FK_TA_SEMESTER FOREIGN KEY (SEMESTER_ID) REFERENCES OMNI_FLEX.SEMESTERS(SEMESTER_ID),
    CONSTRAINT FK_TA_ASSIGNED FOREIGN KEY (ASSIGNED_BY) REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.ENROLLMENTS (
    ENROLL_ID   NUMBER PRIMARY KEY,
    STUDENT_ID  VARCHAR2(10) NOT NULL,
    OFFERING_ID VARCHAR2(10) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    STATUS      VARCHAR2(10) DEFAULT 'Registered',
    CONSTRAINT FK_ENROLL_STUDENT  FOREIGN KEY (STUDENT_ID)  REFERENCES OMNI_FLEX.USERS(USER_ID),
    CONSTRAINT FK_ENROLL_OFFERING FOREIGN KEY (OFFERING_ID) REFERENCES OMNI_FLEX.SECTION_OFFERINGS(OFFERING_ID)
);
 
CREATE TABLE OMNI_FLEX.ANNOUNCEMENTS (
    ANNOUNCEMENT_ID VARCHAR2(10) PRIMARY KEY,
    POSTED_BY       VARCHAR2(10) NOT NULL,
    SECTION_ID      VARCHAR2(10),
    TITLE           VARCHAR2(100) NOT NULL,
    CONTENT         VARCHAR2(1000) NOT NULL,
    AUDIENCE        VARCHAR2(20) DEFAULT 'All',
    IS_PINNED       NUMBER(1,0) DEFAULT 0,
    PRIORITY        VARCHAR2(10) DEFAULT 'Normal',
    POST_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ANN_USER FOREIGN KEY (POSTED_BY)  REFERENCES OMNI_FLEX.USERS(USER_ID),
    CONSTRAINT FK_ANN_SEC  FOREIGN KEY (SECTION_ID) REFERENCES OMNI_FLEX.SECTIONS(SECTION_ID)
);
 
CREATE TABLE OMNI_FLEX.ASSIGNMENTS (
    ASSIGNMENT_ID VARCHAR2(10) PRIMARY KEY,
    SECTION_ID    VARCHAR2(10) NOT NULL,
    TITLE         VARCHAR2(50) NOT NULL,
    DESCRIPTION   VARCHAR2(500),
    DUE_DATE      TIMESTAMP NOT NULL,
    CATEGORY      VARCHAR2(20),
    TOTAL_MARKS   NUMBER(3,0) NOT NULL,
    ACTUAL_WTG    NUMBER(4,2) NOT NULL,
    CREATED_BY    VARCHAR2(10) NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ASGN_SECTION FOREIGN KEY (SECTION_ID) REFERENCES OMNI_FLEX.SECTIONS(SECTION_ID),
    CONSTRAINT FK_ASGN_CREATED FOREIGN KEY (CREATED_BY) REFERENCES OMNI_FLEX.USERS(USER_ID),
    CONSTRAINT CHK_ASGN_CAT CHECK (CATEGORY IN ('Quiz','Assignment','Project','Sessional-I','Sessional-II','Final Exam','Lab Task','Hackathon'))
);
 
CREATE TABLE OMNI_FLEX.ATTENDANCE (
    ATTENDANCE_ID   NUMBER PRIMARY KEY,
    ENROLL_ID       NUMBER NOT NULL,
    ATTENDANCE_DATE DATE DEFAULT SYSDATE,
    STATUS          CHAR(1) NOT NULL,
    MARKED_BY       VARCHAR2(10) NOT NULL,
    CONSTRAINT CHK_ATT_STATUS CHECK (STATUS IN ('P','A','L')),
    CONSTRAINT FK_ATT_ENROLL FOREIGN KEY (ENROLL_ID)  REFERENCES OMNI_FLEX.ENROLLMENTS(ENROLL_ID),
    CONSTRAINT FK_ATT_MARKER FOREIGN KEY (MARKED_BY)  REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.RESULTS (
    RESULT_ID        NUMBER PRIMARY KEY,
    STUDENT_ID       VARCHAR2(10) NOT NULL,
    SECTION_ID       VARCHAR2(10) NOT NULL,
    FINAL_GRADE      VARCHAR2(2),
    FINAL_PERCENTAGE NUMBER(5,2),
    CONSTRAINT UNIQUE_RESULT UNIQUE (STUDENT_ID, SECTION_ID),
    CONSTRAINT FK_RES_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES OMNI_FLEX.USERS(USER_ID),
    CONSTRAINT FK_RES_SECTION FOREIGN KEY (SECTION_ID) REFERENCES OMNI_FLEX.SECTIONS(SECTION_ID)
);
 
CREATE TABLE OMNI_FLEX.FILES (
    FILE_ID     NUMBER PRIMARY KEY,
    UPLOADED_BY VARCHAR2(10) NOT NULL,
    FILE_NAME   VARCHAR2(100) NOT NULL,
    FILE_PATH   VARCHAR2(255) NOT NULL,
    FILE_TYPE   VARCHAR2(50),
    FILE_SIZE   NUMBER,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_FILE_USER FOREIGN KEY (UPLOADED_BY) REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.COURSE_POSTS (
    POST_ID    VARCHAR2(10) PRIMARY KEY,
    SECTION_ID VARCHAR2(10) NOT NULL,
    POSTED_BY  VARCHAR2(10) NOT NULL,
    POST_TYPE  VARCHAR2(20),
    TITLE      VARCHAR2(100) NOT NULL,
    CONTENT    VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT CHK_POST_TYPE  CHECK (POST_TYPE IN ('Material','Announcement','Assignment')),
    CONSTRAINT FK_POST_SECTION FOREIGN KEY (SECTION_ID) REFERENCES OMNI_FLEX.SECTIONS(SECTION_ID),
    CONSTRAINT FK_POST_USER    FOREIGN KEY (POSTED_BY)  REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.POST_COMMENTS (
    COMMENT_ID        NUMBER PRIMARY KEY,
    POST_ID           VARCHAR2(10) NOT NULL,
    USER_ID           VARCHAR2(10) NOT NULL,
    PARENT_COMMENT_ID NUMBER,
    CONTENT           VARCHAR2(1000) NOT NULL,
    VISIBILITY        VARCHAR2(10) DEFAULT 'Public',
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CMT_POST   FOREIGN KEY (POST_ID)           REFERENCES OMNI_FLEX.COURSE_POSTS(POST_ID),
    CONSTRAINT FK_CMT_USER   FOREIGN KEY (USER_ID)           REFERENCES OMNI_FLEX.USERS(USER_ID),
    CONSTRAINT FK_CMT_PARENT FOREIGN KEY (PARENT_COMMENT_ID) REFERENCES OMNI_FLEX.POST_COMMENTS(COMMENT_ID)
);
 
CREATE TABLE OMNI_FLEX.POST_FILES (
    POST_FILE_ID NUMBER PRIMARY KEY,
    POST_ID      VARCHAR2(10) NOT NULL,
    FILE_ID      NUMBER NOT NULL,
    CONSTRAINT FK_PF_POST FOREIGN KEY (POST_ID)  REFERENCES OMNI_FLEX.COURSE_POSTS(POST_ID),
    CONSTRAINT FK_PF_FILE FOREIGN KEY (FILE_ID)  REFERENCES OMNI_FLEX.FILES(FILE_ID)
);
 
CREATE TABLE OMNI_FLEX.SUBMISSIONS (
    SUBMISSION_ID  VARCHAR2(10) PRIMARY KEY,
    ASSIGNMENT_ID  VARCHAR2(10) NOT NULL,
    STUDENT_ID     VARCHAR2(10) NOT NULL,
    SUBMIT_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OBTAINED_MARKS NUMBER(5,2),
    OBTAINED_WTG   NUMBER(5,2),
    IS_LATE        NUMBER(1,0) DEFAULT 0,
    GRADED_BY      VARCHAR2(10),
    GRADED_AT      TIMESTAMP,
    LOCKED         NUMBER(1,0) DEFAULT 0,
    CONSTRAINT FK_SUB_ASSIGN  FOREIGN KEY (ASSIGNMENT_ID) REFERENCES OMNI_FLEX.ASSIGNMENTS(ASSIGNMENT_ID),
    CONSTRAINT FK_SUB_STUDENT FOREIGN KEY (STUDENT_ID)   REFERENCES OMNI_FLEX.USERS(USER_ID),
    CONSTRAINT FK_SUB_GRADER  FOREIGN KEY (GRADED_BY)    REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.SUBMISSION_COMMENTS (
    COMMENT_ID    NUMBER PRIMARY KEY,
    SUBMISSION_ID VARCHAR2(10) NOT NULL,
    USER_ID       VARCHAR2(10) NOT NULL,
    CONTENT       VARCHAR2(1000) NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SC_SUB  FOREIGN KEY (SUBMISSION_ID) REFERENCES OMNI_FLEX.SUBMISSIONS(SUBMISSION_ID),
    CONSTRAINT FK_SC_USER FOREIGN KEY (USER_ID)       REFERENCES OMNI_FLEX.USERS(USER_ID)
);
 
CREATE TABLE OMNI_FLEX.SUBMISSION_FILES (
    SUB_FILE_ID   NUMBER PRIMARY KEY,
    SUBMISSION_ID VARCHAR2(10) NOT NULL,
    FILE_ID       NUMBER NOT NULL,
    CONSTRAINT FK_SF_SUB  FOREIGN KEY (SUBMISSION_ID) REFERENCES OMNI_FLEX.SUBMISSIONS(SUBMISSION_ID),
    CONSTRAINT FK_SF_FILE FOREIGN KEY (FILE_ID)       REFERENCES OMNI_FLEX.FILES(FILE_ID)
);
 
CREATE SEQUENCE OMNI_FLEX.OFFERING_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20;
 
-- =====================================================
-- STEP 2 — DEPARTMENTS
-- =====================================================
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('CS',  'Computer Science',        'Dr. Fahad Samad');
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('AI',  'Artificial Intelligence', 'Dr. Rafi');
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('SE',  'Software Engineering',    'Dr. Anaum Hamid');
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('CY',  'Cyber Security',          'Dr. Shahbaz Siddiqui');
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('DS',  'Data Science',            'Dr. Zeeshan Usmani');
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('EE',  'Electrical Engineering',  'Atif Tahir');
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('MG',  'School of Management',    'Dr. Muhammad Shariq');

INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('SH',  'Sciences & Humanities', 'Dr. Shahzad Shaikh');
INSERT INTO OMNI_FLEX.DEPARTMENTS VALUES ('FIN', 'Finance & Accounts',    'Mr. Sarfraz Khan');

-- =====================================================
-- STEP 3 — SEMESTERS
-- =====================================================
INSERT INTO OMNI_FLEX.SEMESTERS VALUES ('SP2025','Spring 2025',TO_DATE('2025-01-20','YYYY-MM-DD'),TO_DATE('2025-06-05','YYYY-MM-DD'),0);
INSERT INTO OMNI_FLEX.SEMESTERS VALUES ('FL2025','Fall 2025',  TO_DATE('2025-08-18','YYYY-MM-DD'),TO_DATE('2025-12-22','YYYY-MM-DD'),0);
INSERT INTO OMNI_FLEX.SEMESTERS VALUES ('SP2026','Spring 2026',TO_DATE('2026-01-26','YYYY-MM-DD'),TO_DATE('2026-06-10','YYYY-MM-DD'),1);
 
-- =====================================================
-- STEP 4 — COURSES (Core or Elective ONLY)
-- =====================================================
INSERT INTO OMNI_FLEX.COURSES VALUES ('CS1002','CS','Programming Fundamentals',              3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CL1002','CS','Programming Fundamentals Lab',          1,'Lab',   'Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('MT1003','SH','Calculus',                              3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('SS1007','SH','Islamic Studies',                       2,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CS1004','CS','Object Oriented Programming',           3,'Theory','Core',    'CS1002', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CL1004','CS','OOP Lab',                               1,'Lab',   'Core',    'CS1002', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('EE1005','EE','Digital Logic Design',                  3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CS2001','CS','Data Structures',                       3,'Theory','Core',    'CS1004', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CL2001','CS','Data Structures Lab',                   1,'Lab',   'Core',    'CS1004', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('MT1004','SH','Linear Algebra',                        3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CS2005','CS','Database Systems',                      3,'Theory','Core',    'CS2001', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CL2005','CS','Database Systems Lab',                  1,'Lab',   'Core',    'CS2001', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('AI2002','AI','Artificial Intelligence',               3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('AIL2002','AI','Artificial Intelligence Lab',          1,'Lab',   'Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CS2006','CS','Operating Systems',                     3,'Theory','Core',    'CS2001', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CS200L','CS','Operating Systems Lab',                 1,'Lab',   'Core',    'CS2001', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('MT2005','SH','Probability and Statistics',            3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('AI3001','AI','Machine Learning',                      3,'Theory','Core',    'AI2002', 1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('SE2001','SE','Software Requirements Eng',             3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('SE2002','SE','Software Design Patterns',              3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CY2001','CY','Network Security',                      3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('CY2002','CY','Cryptography',                          3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('DS2001','DS','Data Mining',                           3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('DS2002','DS','Big Data Analytics',                    3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('EE3001','EE','Embedded Systems',                      3,'Theory','Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('EEL3001','EE','Embedded Systems Lab',                 1,'Lab',   'Core',    NULL,     1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('MG1001','MG','Psychology',                            2,'Theory','Elective',NULL,    1);
INSERT INTO OMNI_FLEX.COURSES VALUES ('MT2005','SH','Probability and Statistics',3,'Theory','Core',NULL,1);

-- =====================================================
-- STEP 5 — INSTRUCTORS (10 — one per dept + extras)
-- Check which departments actually exist
-- =====================================================
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS1','CS','Farooq',  'Hassan',  'farooq@nu.edu.pk',  'hash1', 'Instructor','Active','Professor',          'CS-101','Algorithms');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS2','CS','Sobia',   'Kausar',  'sobia@nu.edu.pk',   'hash2', 'Instructor','Active','Lecturer',           'CS-102','Database');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS3','CS','Atif',    'Ishaq',   'atif@nu.edu.pk',    'hash3', 'Instructor','Active','Assistant Professor','CS-103','OS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS4','AI','Kashif',  'Zafar',   'kashif@nu.edu.pk',  'hash4', 'Instructor','Active','Associate Professor','AI-101','ML');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS5','AI','Mehmood', 'Raza',    'mehmood@nu.edu.pk', 'hash5', 'Instructor','Active','Professor',          'AI-102','Robotics');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS6','SE','Noman',   'Islam',   'noman@nu.edu.pk',   'hash6', 'Instructor','Active','Professor',          'SE-101','Architecture');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS7','CY','Jawwad',  'Shamsi',  'jawwad@nu.edu.pk',  'hash7', 'Instructor','Active','Professor',          'CY-101','Network Security');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS8','DS','Zeeshan', 'Ali',     'zeeshan@nu.edu.pk', 'hash8', 'Instructor','Active','Assistant Professor','DS-101','Data Analytics');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS9','EE','Tahir',   'Qadri',   'tahir@nu.edu.pk',   'hash9', 'Instructor','Active','Assistant Professor','EE-101','Circuits');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION,OFFICE_ROOM,SPECIALIZATION) VALUES ('INS10','SH','Bilal',  'Saeed',   'bilal@nu.edu.pk',   'hash10','Instructor','Active','Assistant Professor','SH-101','Physics');
 
-- =====================================================
-- STEP 6 — ADMIN (3 records)
-- =====================================================
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION) VALUES ('ADM-001','CS', 'Sufyan','Ahsan', 'sufyan.admin@nu.edu.pk','admin_123','Admin','Active','Academics Admin');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION) VALUES ('ADM-002','FIN','Sajid', 'Ali',   'finance.admin@nu.edu.pk','admin_123','Admin','Active','Accountant');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,DESIGNATION) VALUES ('ADM-003','SH', 'Hina',  'Nasir', 'hina.admin@nu.edu.pk',  'admin_123','Admin','Active','Academic Coordinator');
 
-- =====================================================
-- STEP 7 — STUDENTS
-- CS=8, AI=4, SE=3, CY=3, DS=3, EE=2 = 23 students
-- TA students at bottom (older batch, Role=Student)
-- =====================================================
 
-- CS (8 students)
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0524','CS','Duaa',     'Siraj',   'k240524@nu.edu.pk','hash_s1','Student','Active',   2024,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0571','CS','Faizan',   'Basheer', 'k240571@nu.edu.pk','hash_s2','Student','Active',   2024,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0767','CS','Abdur',    'Rehman',  'k240767@nu.edu.pk','hash_s3','Student','Active',   2024,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0806','CS','Muhammad', 'Sufyan',  'k240806@nu.edu.pk','hash_s4','Student','Active',   2024,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0815','CS','Ahmed',    'Raza',    'k240815@nu.edu.pk','hash_s5','Student','Active',   2024,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0876','CS','Muhammad', 'Jaseem',  'k240876@nu.edu.pk','hash_s6','Student','Active',   2024,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0904','CS','Abdullah', 'Chohan',  'k240904@nu.edu.pk','hash_s7','Student','Active',   2024,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0963','CS','Zainab',   'Batool',  'k240963@nu.edu.pk','hash_s8','Student','Withdrawn',2024,'BSCS');
 
-- AI (4 students)
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0537','AI','Ruhab',   'Farooq',   'k240537@nu.edu.pk','hash_s9', 'Student','Active',2024,'BSAI');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0560','AI','Wania',   'Nehal',    'k240560@nu.edu.pk','hash_s10','Student','Active',2024,'BSAI');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0642','AI','Aayan',   'Mahmood',  'k240642@nu.edu.pk','hash_s11','Student','Active',2024,'BSAI');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0706','AI','Muhammad','Taha',      'k240706@nu.edu.pk','hash_s12','Student','Active',2024,'BSAI');
 
-- SE (3 students)
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0811','SE','Kashan',  'Ghouri',  'k240811@nu.edu.pk','hash_s13','Student','Active',2024,'BSSE');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0857','SE','Wareesha','Khatri',   'k240857@nu.edu.pk','hash_s14','Student','Active',2024,'BSSE');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0862','SE','Musab',   'Shaikh',   'k240862@nu.edu.pk','hash_s15','Student','Active',2024,'BSSE');
 
-- CY (3 students)
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0686','CY','Syed',   'Muhammad','k240686@nu.edu.pk','hash_s16','Student','Active',2024,'BSCY');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0931','CY','Mehdi',  'Raza',    'k240931@nu.edu.pk','hash_s17','Student','Active',2024,'BSCY');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0942','CY','Faraz',  'Ahmed',   'k240942@nu.edu.pk','hash_s18','Student','Active',2024,'BSCY');
 
-- DS (3 students)
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0903','DS','Manal',  'Zehra',   'k240903@nu.edu.pk','hash_s19','Student','Active',2024,'BSDS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0911','DS','Akshay', 'Kumar',   'k240911@nu.edu.pk','hash_s20','Student','Active',2024,'BSDS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-1032','DS','Zaid',   'Qureshi', 'k241032@nu.edu.pk','hash_s21','Student','Active',2024,'BSDS');
 
-- EE (2 students)
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0662','EE','Mustafa','Rehan',  'k240662@nu.edu.pk','hash_s22','Student','Withdrawn',2024,'BSEE');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('24K-0984','EE','Hasan',  'Nawaz',  'k240984@nu.edu.pk','hash_s23','Student','Active',   2024,'BSEE');
 
-- TA Students (older batch — identified via SECTION_TAS, Role=Student)
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('22K-1001','CS','Hamza',  'Iqbal',   'k221001@nu.edu.pk','hash_ta1','Student','Active',2022,'BSCS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('22K-1002','AI','Zainab', 'Malik',   'k221002@nu.edu.pk','hash_ta2','Student','Active',2022,'BSAI');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('23K-0501','CY','Hassan', 'Zahid',   'k230501@nu.edu.pk','hash_ta3','Student','Active',2023,'BSCY');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('23K-0502','DS','Mehak',  'Imran',   'k230502@nu.edu.pk','hash_ta4','Student','Active',2023,'BSDS');
INSERT INTO OMNI_FLEX.USERS (USER_ID,DEPT_ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS,BATCH,DEGREE) VALUES ('22K-1003','SE','Ahmed',  'Feroz',   'k221003@nu.edu.pk','hash_ta5','Student','Active',2022,'BSSE');
 
-- =====================================================
-- STEP 8 — SECTIONS (one per department)
-- =====================================================
INSERT INTO OMNI_FLEX.SECTIONS VALUES ('BCS-4G','4G','CS','BSCS',2024,'24K-0876');
INSERT INTO OMNI_FLEX.SECTIONS VALUES ('BCS-4J','4J','CS','BSCS',2024,'24K-0806');
INSERT INTO OMNI_FLEX.SECTIONS VALUES ('BAI-4A','4A','AI','BSAI',2024,'24K-0560');
INSERT INTO OMNI_FLEX.SECTIONS VALUES ('BSE-4A','4A','SE','BSSE',2024,'24K-0857');
INSERT INTO OMNI_FLEX.SECTIONS VALUES ('BCY-4A','4A','CY','BSCY',2024,'24K-0931');
INSERT INTO OMNI_FLEX.SECTIONS VALUES ('BDS-4A','4A','DS','BSDS',2024,'24K-1032');
INSERT INTO OMNI_FLEX.SECTIONS VALUES ('BEE-4A','4A','EE','BSEE',2024,'24K-0984');
 
-- =====================================================
-- STEP 9 — SECTION OFFERINGS (SP2026 current semester)
-- =====================================================
-- BCS-4G
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-501','BCS-4G','CS2005','SP2026','INS2', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-502','BCS-4G','CL2005','SP2026','INS1', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-503','BCS-4G','CS2006','SP2026','INS3', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-504','BCS-4G','AI2002','SP2026','INS4', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-505','BCS-4G','MT2005','SP2026','INS10',50);
-- BCS-4J
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-506','BCS-4J','CS2005','SP2026','INS1', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-507','BCS-4J','CL2005','SP2026','INS2', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-508','BCS-4J','CS2006','SP2026','INS3', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-509','BCS-4J','AI2002','SP2026','INS5', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-510','BCS-4J','MT2005','SP2026','INS10',50);
-- BAI-4A
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-511','BAI-4A','AI2002', 'SP2026','INS4', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-512','BAI-4A','AIL2002','SP2026','INS5', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-513','BAI-4A','AI3001', 'SP2026','INS4', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-514','BAI-4A','CS2005', 'SP2026','INS1', 50);
-- BSE-4A
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-515','BSE-4A','SE2001','SP2026','INS6', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-516','BSE-4A','SE2002','SP2026','INS6', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-517','BSE-4A','CS2005','SP2026','INS2', 50);
-- BCY-4A
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-518','BCY-4A','CY2001','SP2026','INS7', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-519','BCY-4A','CY2002','SP2026','INS7', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-520','BCY-4A','CS2005','SP2026','INS1', 50);
-- BDS-4A
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-521','BDS-4A','DS2001','SP2026','INS8', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-522','BDS-4A','DS2002','SP2026','INS8', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-523','BDS-4A','CS2005','SP2026','INS2', 50);
-- BEE-4A
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-524','BEE-4A','EE3001', 'SP2026','INS9', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-525','BEE-4A','EEL3001','SP2026','INS9', 50);
INSERT INTO OMNI_FLEX.SECTION_OFFERINGS VALUES ('SO-526','BEE-4A','MT2005', 'SP2026','INS10',50);
 
 
-- =====================================================
-- STEP 10 — SECTION TAS
INSERT INTO OMNI_FLEX.SECTION_TAS VALUES ('TA-01','BCS-4G','22K-1001','CS2005','SP2026','INS2',SYSDATE);
INSERT INTO OMNI_FLEX.SECTION_TAS VALUES ('TA-02','BAI-4A','22K-1002','AI2002','SP2026','INS4',SYSDATE);
INSERT INTO OMNI_FLEX.SECTION_TAS VALUES ('TA-03','BCY-4A','23K-0501','CY2001','SP2026','INS7',SYSDATE);
INSERT INTO OMNI_FLEX.SECTION_TAS VALUES ('TA-04','BDS-4A','23K-0502','DS2001','SP2026','INS8',SYSDATE);
INSERT INTO OMNI_FLEX.SECTION_TAS VALUES ('TA-05','BSE-4A','22K-1003','SE2001','SP2026','INS6',SYSDATE);
-- =====================================================


-- =====================================================
-- STEP 11 — ENROLLMENTS
-- =====================================================
-- BCS-4G 
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (101,'24K-0767','SO-501',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (102,'24K-0767','SO-502',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (103,'24K-0767','SO-503',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (104,'24K-0767','SO-504',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (105,'24K-0767','SO-505',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (106,'24K-0876','SO-501',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (107,'24K-0876','SO-503',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (108,'24K-0524','SO-501',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (109,'24K-0524','SO-502',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (110,'24K-0571','SO-501',SYSDATE,'Registered');

-- BCS-4J 
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (111,'24K-0806','SO-506',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (112,'24K-0806','SO-507',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (113,'24K-0806','SO-508',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (114,'24K-0806','SO-509',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (115,'24K-0806','SO-510',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (116,'24K-0904','SO-506',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (117,'24K-0904','SO-508',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (118,'24K-0815','SO-506',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (119,'24K-0963','SO-506',SYSDATE,'Dropped');

-- BAI-4A
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (120,'24K-0560','SO-511',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (121,'24K-0560','SO-512',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (122,'24K-0560','SO-513',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (123,'24K-0560','SO-514',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (124,'24K-0537','SO-511',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (125,'24K-0642','SO-513',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (126,'24K-0706','SO-514',SYSDATE,'Registered');
-- BSE-4A
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (127,'24K-0811','SO-515',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (128,'24K-0811','SO-516',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (129,'24K-0857','SO-515',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (130,'24K-0862','SO-517',SYSDATE,'Registered');

-- BCY-4A
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (131,'24K-0686','SO-518',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (132,'24K-0686','SO-519',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (133,'24K-0931','SO-518',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (134,'24K-0942','SO-520',SYSDATE,'Registered');

-- BDS-4A
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (135,'24K-0903','SO-521',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (136,'24K-0903','SO-522',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (137,'24K-0911','SO-521',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (138,'24K-1032','SO-523',SYSDATE,'Registered');

-- BEE-4A
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (139,'24K-0984','SO-524',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (140,'24K-0984','SO-525',SYSDATE,'Registered');
INSERT INTO OMNI_FLEX.ENROLLMENTS VALUES (141,'24K-0984','SO-526',SYSDATE,'Registered');

COMMIT;
rollback;
SELECT COUNT(*) FROM COURSES;
ALTER SESSION SET CURRENT_SCHEMA = OMNI_FLEX;
SELECT DISTINCT ROLE FROM OMNI_FLEX.USERS;